CREATE TABLE MT_ALERTAS
    (
     ID_ALERTA   NUMBER (19)  NOT NULL ,
     DATA_ALERTA TIMESTAMP  NOT NULL ,
     GRAVIDADE   VARCHAR2 (255 CHAR)  NOT NULL ,
     MENSAGEM    VARCHAR2 (200 CHAR)  NOT NULL ,
     MOTO_ID     NUMBER (19)
    )
        PCTFREE 10
        PCTUSED 40
        TABLESPACE TBSPC_ALUNOS
        LOGGING
        STORAGE (
        INITIAL 65536
        NEXT 1048576
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645
        FREELISTS 1
        FREELIST GROUPS 1
        BUFFER_POOL DEFAULT
    )
    NO INMEMORY
;

ALTER TABLE MT_ALERTAS
    ADD
    CHECK (GRAVIDADE IN ('ALTA', 'BAIXA', 'MEDIA'))
;

ALTER TABLE MT_ALERTAS
    ADD CONSTRAINT MT_ALERTAS_PK PRIMARY KEY ( ID_ALERTA )
    USING INDEX
        PCTFREE 10
        INITRANS 2
        TABLESPACE TBSPC_ALUNOS
        LOGGING
        STORAGE (
        INITIAL 65536
        NEXT 1048576
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645
        FREELISTS 1
        FREELIST GROUPS 1
        BUFFER_POOL DEFAULT
    ) ;