CREATE TABLE MT_MOTOS
    (
     ID_MOTO NUMBER (19)  NOT NULL ,
     CHASSI  VARCHAR2 (17 CHAR)  NOT NULL ,
     MODELO  VARCHAR2 (11 CHAR)  NOT NULL ,
     PLACA   VARCHAR2 (7 CHAR)  NOT NULL ,
     STATUS  VARCHAR2 (30 CHAR)  NOT NULL
    )
        PCTFREE 10
        PCTUSED 40
        TABLESPACE TBSPC_ALUNOS
        LOGGING
        STORAGE (
        INITIAL 65536
        NEXT 1048576
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645
        FREELISTS 1
        FREELIST GROUPS 1
        BUFFER_POOL DEFAULT
    )
    NO INMEMORY
;

ALTER TABLE MT_MOTOS
    ADD
    CHECK (MODELO IN ('MOTTU_E', 'MOTTU_POP', 'MOTTU_SPORT'))
;

ALTER TABLE MT_MOTOS
    ADD CONSTRAINT STATUS_CHK
    CHECK (STATUS IN ('AVALIACAO', 'MANUTENCAO', 'DISPONIVEL'))
;
CREATE UNIQUE INDEX UK_MT_MOTOS_PLACA  ON MT_MOTOS
    (
     PLACA ASC
    )
    TABLESPACE TBSPC_ALUNOS
    PCTFREE 10
    STORAGE (
        INITIAL 65536
        NEXT 1048576
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645
        FREELISTS 1
        FREELIST GROUPS 1
        BUFFER_POOL DEFAULT )
    LOGGING
;
CREATE UNIQUE INDEX UK_MT_MOTOS_CHASSI ON MT_MOTOS
    (
     CHASSI ASC
    )
    TABLESPACE TBSPC_ALUNOS
    PCTFREE 10
    STORAGE (
        INITIAL 65536
        NEXT 1048576
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645
        FREELISTS 1
        FREELIST GROUPS 1
        BUFFER_POOL DEFAULT )
    LOGGING
;

ALTER TABLE MT_MOTOS
    ADD CONSTRAINT MT_MOTOS_PK PRIMARY KEY ( ID_MOTO )
    USING INDEX
        PCTFREE 10
        INITRANS 2
        TABLESPACE TBSPC_ALUNOS
        LOGGING
        STORAGE (
        INITIAL 65536
        NEXT 1048576
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645
        FREELISTS 1
        FREELIST GROUPS 1
        BUFFER_POOL DEFAULT
    ) ;

ALTER TABLE MT_MOTOS
    ADD CONSTRAINT UK_MT_MOTOS_PLACA_UQ  UNIQUE ( PLACA )
    USING INDEX UK_MT_MOTOS_PLACA ;

ALTER TABLE MT_MOTOS
    ADD CONSTRAINT UK_MT_MOTOS_CHASSI_UQ UNIQUE ( CHASSI )
    USING INDEX UK_MT_MOTOS_CHASSI ;