INSERT INTO MT_DEPARTAMENTOS (ID_DEPARTAMENTO, DESCRICAO, TIPO)
VALUES (1, 'Entrada do pátio', 'ENTRADA');

INSERT INTO MT_DEPARTAMENTOS (ID_DEPARTAMENTO, DESCRICAO, TIPO)
VALUES (2, 'Departamento de Avaliação', 'AVALIACAO');

INSERT INTO MT_DEPARTAMENTOS (ID_DEPARTAMENTO, DESCRICAO, TIPO)
VALUES (3, 'Departamento de Manutenção', 'MANUTENCAO');

INSERT INTO MT_DEPARTAMENTOS (ID_DEPARTAMENTO, DESCRICAO, TIPO)
VALUES (4, 'Departamento Pronto para Uso', 'PRONTA_PARA_USO');

INSERT INTO MT_DEPARTAMENTOS (ID_DEPARTAMENTO, DESCRICAO, TIPO)
VALUES (5, 'Saída do pátio', 'SAIDA');