CREATE TABLE MT_DEPARTAMENTOS
    (
     ID_DEPARTAMENTO NUMBER (19)  NOT NULL ,
     DESCRICAO       VARCHAR2 (100 CHAR)  NOT NULL ,
     TIPO            VARCHAR2 (30 CHAR)  NOT NULL
    )
        PCTFREE 10
        PCTUSED 40
        TABLESPACE TBSPC_ALUNOS
        LOGGING
        STORAGE (
        INITIAL 65536
        NEXT 1048576
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645
        FREELISTS 1
        FREELIST GROUPS 1
        BUFFER_POOL DEFAULT
    )
    NO INMEMORY
;

ALTER TABLE MT_DEPARTAMENTOS
    ADD
    CHECK (TIPO IN ('AVALIACAO', 'ENTRADA', 'MANUTENCAO', 'PRONTA_PARA_USO', 'SAIDA'))
;

ALTER TABLE MT_DEPARTAMENTOS
    ADD CONSTRAINT MT_DEPARTAMENTOS_PK PRIMARY KEY ( ID_DEPARTAMENTO )
    USING INDEX
        PCTFREE 10
        INITRANS 2
        TABLESPACE TBSPC_ALUNOS
        LOGGING
        STORAGE (
        INITIAL 65536
        NEXT 1048576
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645
        FREELISTS 1
        FREELIST GROUPS 1
        BUFFER_POOL DEFAULT
    ) ;