CREATE TABLE MT_MOVIMENTACOES
    (
     ID_MOVIMENTACAO   NUMBER (19)  NOT NULL ,
     DATA_MOVIMENTACAO TIMESTAMP ,
     DEPARTAMENTO_ID   NUMBER (19) ,
     MOTO_ID           NUMBER (19)
    )
        PCTFREE 10
        PCTUSED 40
        TABLESPACE TBSPC_ALUNOS
        LOGGING
        STORAGE (
        INITIAL 65536
        NEXT 1048576
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645
        FREELISTS 1
        FREELIST GROUPS 1
        BUFFER_POOL DEFAULT
    )
    NO INMEMORY
;

ALTER TABLE MT_MOVIMENTACOES
    ADD CONSTRAINT MT_MOVIMENTACOES_PK PRIMARY KEY ( ID_MOVIMENTACAO )
    USING INDEX
        PCTFREE 10
        INITRANS 2
        TABLESPACE TBSPC_ALUNOS
        LOGGING
        STORAGE (
        INITIAL 65536
        NEXT 1048576
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645
        FREELISTS 1
        FREELIST GROUPS 1
        BUFFER_POOL DEFAULT
    ) ;