CREATE TABLE MT_USUARIOS
    (
     ID_USUARIO   NUMBER (19)  NOT NULL ,
     DATA_CRIACAO TIMESTAMP ,
     EMAIL        VARCHAR2 (150 CHAR)  NOT NULL ,
     NOME         VARCHAR2 (150 CHAR)  NOT NULL ,
     SENHA        VARCHAR2 (150 CHAR)  NOT NULL ,
     PERFIL       VARCHAR2 (20 CHAR)  NOT NULL
    )
        PCTFREE 10
        PCTUSED 40
        TABLESPACE TBSPC_ALUNOS
        LOGGING
        STORAGE (
        INITIAL 65536
        NEXT 1048576
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645
        FREELISTS 1
        FREELIST GROUPS 1
        BUFFER_POOL DEFAULT
    )
    NO INMEMORY
;

ALTER TABLE MT_USUARIOS
    ADD
    CHECK (PERFIL IN ('ADMIN', 'COMUM'))
;
CREATE UNIQUE INDEX EMAIL_UNIQUE ON MT_USUARIOS
    (
     EMAIL ASC
    )
    TABLESPACE TBSPC_ALUNOS
    PCTFREE 10
    STORAGE (
        INITIAL 65536
        NEXT 1048576
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645
        FREELISTS 1
        FREELIST GROUPS 1
        BUFFER_POOL DEFAULT )
    LOGGING
;

ALTER TABLE MT_USUARIOS
    ADD CONSTRAINT MT_USUARIOS_PK PRIMARY KEY ( ID_USUARIO )
    USING INDEX
        PCTFREE 10
        INITRANS 2
        TABLESPACE TBSPC_ALUNOS
        LOGGING
        STORAGE (
        INITIAL 65536
        NEXT 1048576
        PCTINCREASE 0
        MINEXTENTS 1
        MAXEXTENTS 2147483645
        FREELISTS 1
        FREELIST GROUPS 1
        BUFFER_POOL DEFAULT
    ) ;

ALTER TABLE MT_USUARIOS
    ADD CONSTRAINT EMAIL_UNIQUE UNIQUE ( EMAIL )
    USING INDEX EMAIL_UNIQUE ;