ALTER TABLE MT_ALERTAS
    ADD CONSTRAINT FK_MT_ALERTAS_MT_MOTOS FOREIGN KEY
    (
     MOTO_ID
    )
    REFERENCES MT_MOTOS
    (
     ID_MOTO
    )
    NOT DEFERRABLE
;

ALTER TABLE MT_MOVIMENTACOES
    ADD CONSTRAINT FK_MT_MOVIMENTACOES_MT_MOTOS FOREIGN KEY
    (
     MOTO_ID
    )
    REFERENCES MT_MOTOS
    (
     ID_MOTO
    )
    NOT DEFERRABLE
;

ALTER TABLE MT_MOVIMENTACOES
    ADD CONSTRAINT FK_MT_MOVIMENTACOES_MT_DEPARTAMENTOS FOREIGN KEY
    (
     DEPARTAMENTO_ID
    )
    REFERENCES MT_DEPARTAMENTOS
    (
     ID_DEPARTAMENTO
    )
    NOT DEFERRABLE
;