INSERT INTO MT_DEPARTAMENTOS (ID_DEPARTAMENTO, DESCRICAO, TIPO)
VALUES (SEQ_MT_DEPARTAMENTOS.NEXTVAL, 'Entrada do pátio', 'ENTRADA');

INSERT INTO MT_DEPARTAMENTOS (ID_DEPARTAMENTO, DESCRICAO, TIPO)
VALUES (SEQ_MT_DEPARTAMENTOS.NEXTVAL, 'Departamento de Avaliação', 'AVALIACAO');

INSERT INTO MT_DEPARTAMENTOS (ID_DEPARTAMENTO, DESCRICAO, TIPO)
VALUES (SEQ_MT_DEPARTAMENTOS.NEXTVAL, 'Departamento de Manutenção', 'MANUTENCAO');

INSERT INTO MT_DEPARTAMENTOS (ID_DEPARTAMENTO, DESCRICAO, TIPO)
VALUES (SEQ_MT_DEPARTAMENTOS.NEXTVAL, 'Departamento Pronto para Uso', 'PRONTA_PARA_USO');

INSERT INTO MT_DEPARTAMENTOS (ID_DEPARTAMENTO, DESCRICAO, TIPO)
VALUES (SEQ_MT_DEPARTAMENTOS.NEXTVAL, 'Saída do pátio', 'SAIDA');